POST  http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "hungvo",
  "password": "123456"
}


###
POST  http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "hungvo",
  "password": "123456"
}
