POST  http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "hungvo2",
  "password": "123456"
}


###
POST  http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "hungvo",
  "password": "123456"
}


###
POST  http://localhost:5000/api/product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDJkYTZlNjM2MDIzNzU5NDEyNmNjZDkiLCJpYXQiOjE2ODE4MTA2MDJ9.zsY80o8ygDCHqtLngmo7-x4mYiQUaeXdwtpXDSMRWW4

{
  "name": "Cappucino",
  "price": 10,
  "star": 4.7,
  "category": ["Cold", "Hot"],
  "imgUrl": "https://plus.unsplash.com/premium_photo-1673107321914-d1c327b86fce?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=765&q=80"
}


###
GET  http://localhost:5000/api/product


###
GET  http://localhost:5000/api/cart



###
POST http://localhost:5000/api/cart/addToCart
Content-Type: application/json

{
  "productId": "6432e45bf6e8648fde8509c9",
  "quantity": 2
}

###
POST http://localhost:5000/api/cart/emptyCart



###
PUT http://localhost:5000/api/product/643e652d269a1e84faa53415
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDJkYTZlNjM2MDIzNzU5NDEyNmNjZDkiLCJpYXQiOjE2ODE4MTA2MDJ9.zsY80o8ygDCHqtLngmo7-x4mYiQUaeXdwtpXDSMRWW4

{
  "name": "Cappucino",
  "price": 9,
  "star": 4.8,
  "category": ["Cold", "Hot"],
  "imgUrl": "https://plus.unsplash.com/premium_photo-1673107321914-d1c327b86fce?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=765&q=80"
}

###
DELETE  http://localhost:5000/api/product/643e652d269a1e84faa53415
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDJkYTZlNjM2MDIzNzU5NDEyNmNjZDkiLCJpYXQiOjE2ODE4MTA2MDJ9.zsY80o8ygDCHqtLngmo7-x4mYiQUaeXdwtpXDSMRWW4





